basicApp/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from basicApp import views

# TEMPLATE URLS
app_name = 'basicApp'

urlpatterns = [
    re_path( r'register/$', views.register, name='register' ),
    re_path( '^user_login/$', views.user_login, name='user_login' )
]

learningUsers/urls.py
from django.contrib import admin
from django.conf.urls  import include
from django.urls import path, re_path
from basicApp import views

urlpatterns = [
    re_path( r'^$', views.index, name='index' ),
    path('admin/', admin.site.urls),
    re_path( '^basicApp/', include( 'basicApp.urls' ) ),
    re_path( '^logout/$', views.user_logout, name='logout' )
]

basicApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo( models.Model ):
    """
    Dummy
    """
    user = models.OneToOneField( User, on_delete=models.CASCADE )

    # additional
    portfolio_site = models.URLField( blank = True )
    profile_pic = models.ImageField( upload_to='profile_pics', blank = True )

    def __str__( self ):
        return self.user.username

basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo 

class UserForm( forms.ModelForm ):
    password = forms.CharField( widget = forms.PasswordInput() )
    
    class Meta():
        model = User
        fields = ( 'username', 'email', 'password' )

class UserProfileInfoForm( forms.ModelForm ):
    
    class Meta():
        model = UserProfileInfo
        fields = ( 'portfolio_site', 'profile_pic' )

basicApp/views.py
"""
Dummy
"""
from django.shortcuts import render
from basicApp.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index( request ):
    return render( request, 'basicApp/index.html' )

@login_required
def user_logout( request ):
    logout( request )
    return HttpResponseRedirect( reverse( 'index' ) )

def register( request ):
    """ Dummy """
    registered = False

    if request.method == "POST":

        user_form = UserForm( data = request.POST )
        profile_form = UserProfileInfoForm( data = request.POST )

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password( user.password )
            user.save()

            profile = profile_form.save( commit = False )
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES[ 'profile_pic' ]

            profile.save()

            registered = True
        else:
            print( user_form.errors, profile_form.errors )
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render( request,
                   'basicApp/registration.html',
                   { 'user_form'   : user_form,
                     'profile_form': profile_form,
                     'registered'  : registered,
                   }
                 )

def user_login( request ):

    if request.method == "POST":

        username = request.POST.get( 'username' )
        password = request.POST.get( 'password' )

        user = authenticate( username = username, password = password )

        if user:
            if user.is_active:
                login( request, user )
                return HttpResponseRedirect( reverse( 'index' ) )
            else:
                return HttpResponse( "Account not active!" )
        else:
            print( "Attempted login failed!" )
            print( "Username: {} and password {}".format( username, password) )
            return HttpResponse( "Inlvalid log-in details supplied!" )

    return render( request, 'basicApp/login.html', {} )

templates/basicApp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li> <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li> <a class="navbar-link" href="{% url 'basicApp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li> <a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li> <a class="navbar-link" href="{% url 'basicApp:user_login' %}">Log in</a></li>
          {% endif %}

        </ul>
      </div>
    <nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

  </body>
</html>

templates/basicApp/index.html
{% extends "basicApp/base.html" %}
{% block body_block %}
<div class=jumbotron>
    <h1>Index page</h1>
</div>
{% endblock %}

templates/basicApp/login.html
{% extends "basicApp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please log in</h1>
    <form action="{% url 'basicApp:user_login' %}" method="POST">
        {% csrf_token %}

        <label for="username">User name:</label>
        <input type="text" name="username" placeholder="Enter user name">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" name="" value="Login">

    </form>
</div>

{% endblock %}

templates/basicApp/registration.html
{% extends "basicApp/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class=jumbotron>

    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register here</h1>
        <h3>Fill in the form:</h3>
        
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="" value="register"/>

        </form>

    {% endif %}

</div>
{% endblock %}